-- supabase/migrations/001_initial_schema.sql
-- This is auto-generated by Prisma. Run `npm run db:push` instead of running this manually.
-- Kept here for reference only.

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- The full schema is managed by Prisma (prisma/schema.prisma).
-- Run: npm run db:push
-- to apply the schema to your Supabase database.
